"""Generate js/art/sprites.js: player poses, ball frames and shadow from the original game.

Poses and their offsets come from the frame dumps in tools/data/, the ball frames from the
reference recording, the CHR tiles and palettes from the screen capture (see tools/recording.py).
Python 3.10+, stdlib only.

  py tools/gen_sprites.py
"""
import argparse
from collections import Counter
from pathlib import Path

from recording import (BALL, BALL_PALETTE, DEFAULT_SCREEN, GAMEPLAY_POSES, PLAYER, PLAYER_PALETTE, ROOT,
                       SHADOW_TILE, SPRITE_LAG, Screen, recordings)

# Player and ball x on the first tick of the screen (the recordings all start later on).
START_PLAYER_X = 121
START_BALL_X = 133

# NES palette entries used by the sprites, in the colours of docs/reference/nsl-jp.gif.
GIF_COLOURS = {0x0F: "#000000", 0x30: "#fffeff", 0x26: "#fe8170"}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--screen", type=Path, default=DEFAULT_SCREEN)
    ap.add_argument("--out", type=Path, default=ROOT / "js" / "art" / "sprites.js")
    args = ap.parse_args()

    recs = recordings()
    rec, dump = recs[0], recs[0].dump
    screen = Screen(args.screen)
    sig_by_id = {pid: sig for r in recs for sig, pid in r.pose_ids.items()}
    # The reference recording's poses past the gameplay ones only appear in the transition after START.
    transition = {pid for pid in rec.pose_ids.values() if pid >= GAMEPLAY_POSES}
    poses = sorted(set(sig_by_id) - transition)
    if poses != list(range(len(poses))):
        raise SystemExit(f"pose ids are not contiguous: {poses}")

    offsets = {}
    for r in recs:
        for f in range(SPRITE_LAG, len(r.dump)):
            entry = r.timeline[f]
            if entry and entry[0] in poses:
                pid, facing, sx, sy = entry
                key = (sx - int(r.x(f - SPRITE_LAG, PLAYER)), sy + int(r.z(f - SPRITE_LAG, PLAYER)))
                offsets.setdefault((pid, facing), Counter())[key] += 1

    def width(pid):
        return max(p[0] for p in sig_by_id[pid]) + 8

    # Poses seen in both facings all satisfy dxLeft + dxRight + width = c; use it for the others.
    known = Counter()
    for pid in poses:
        if (pid, "left") in offsets and (pid, "right") in offsets:
            known[offsets[(pid, "left")].most_common(1)[0][0][0] + offsets[(pid, "right")].most_common(1)[0][0][0] + width(pid)] += 1
    if len(known) != 1:
        raise SystemExit(f"mirror offsets are not consistent: {dict(known)}")
    c = next(iter(known))

    used_tiles = {SHADOW_TILE}
    pose_js = []
    for pid in poses:
        sig = sig_by_id[pid]
        w, h = width(pid), max(p[1] for p in sig) + 8
        used_tiles.update(p[2] for p in sig)
        off = {f: list(offsets[(pid, f)].most_common(1)[0][0]) for f in ("left", "right") if (pid, f) in offsets}
        for facing, other in (("left", "right"), ("right", "left")):
            if facing not in off:
                off[facing] = [c - w - off[other][0], off[other][1]]
        parts = ", ".join(f"[{dx}, {dy}, 0x{t:02x}, {int(hf)}, {int(vf)}]" for dx, dy, t, hf, vf in sig)
        pose_js.append(f"  {{ width: {w}, height: {h}, left: [{off['left'][0]}, {off['left'][1]}], right: [{off['right'][0]}, {off['right'][1]}],\n    parts: [{parts}] }},")

    # --- ball rotation frames (4 sprites each), most common first
    ball_frames = Counter()
    for f in range(len(dump)):
        b = [(sx, sy, t, a) for sx, sy, t, a in dump.sprites(f) if a & 3 == BALL_PALETTE]
        if len(b) == 4:
            x0, y0 = min(p[0] for p in b), min(p[1] for p in b)
            ball_frames[tuple(sorted((sx - x0, sy - y0, t, bool(a & 0x40), bool(a & 0x80)) for sx, sy, t, a in b))] += 1
    ball_js = []
    for sig, n in ball_frames.most_common():
        used_tiles.update(p[2] for p in sig)
        ball_js.append("  [" + ", ".join(f"[{dx}, {dy}, 0x{t:02x}, {int(hf)}, {int(vf)}]" for dx, dy, t, hf, vf in sig) + f"],  // {n} frames")

    tile_js = []
    for t in sorted(used_tiles):
        rows = screen.sprite_tile(t)
        tile_js.append(f"  0x{t:02x}: [" + ", ".join("'" + "".join(str(v) for v in row) + "'" for row in rows) + "],")

    def palette(p):
        return "[null, " + ", ".join(f"'{GIF_COLOURS[screen.sprite_colour_index(p, i)]}'" for i in (1, 2, 3)) + "]"

    nl = "\n"
    js = f"""// Player, ball and shadow sprites from the original ROM (CHR + palettes captured in Mesen),
// with poses and offsets measured from a frame dump of the ball-practice screen.
// Generated by tools/gen_sprites.py; do not edit by hand.
// Coordinates are NES pixels. A part is [dx, dy, tile, flipH, flipV]; tiles are rows of 2-bit
// palette indices (0 = transparent). Poses are stored facing left; `left`/`right` give the
// sprite's top-left as [x offset from int(X), OAM y + int(Z)] for each facing.

export const PALETTES = {{
  player: {palette(PLAYER_PALETTE)},
  ball: {palette(BALL_PALETTE)},
}};

export const TILES = {{
{nl.join(tile_js)}
}};

export const PLAYER_POSES = [
{nl.join(pose_js)}
];

// Rotation frames, most common first; drawn at [int(X) - 8, 149 - int(Z)] (OAM y).
export const BALL_FRAMES = [
{nl.join(ball_js)}
];

// One tile under an airborne object at [int(X) - 4, OAM y]: 156 for the player, 157 for the ball.
export const SHADOW = {{ tile: 0x{SHADOW_TILE:02x}, playerY: 156, ballY: 157 }};

// As the screen opens: the ball at the player's feet (tools/simulate.py, the idle plan).
export const START = {{
  playerX: {START_PLAYER_X},
  ballX: {START_BALL_X},
}};
"""
    args.out.write_text(js, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}: {len(used_tiles)} tiles, {len(pose_js)} poses, {len(ball_js)} ball frames")


if __name__ == "__main__":
    main()
